### ISSUE TITLE
Cannot invoke method encodeAsSlug() on null object

### ISSUE THREAD

**Issue by emmanuelrosa** [sysgears/grain-theme-octopress#8]
After creating the stub for my first post I got the following exception when running Grain in preview mode: `Rebuilding url->resource map
java.lang.NullPointerException: Cannot invoke method encodeAsSlug() on null object`

It seems like the post title is null, but I don't understand why. I added the following to the post but I still got the same error:

```yaml
---
layout: post
title: "GORM for SQLaddicts: WHERE Clause"
date: "2015-10-07 15:59"
author: "Emmanuel Rosa"
categories: [gorm, sqladdicts]
comments: false 
published: false
---
```

# How to reproduce
I'm using grain-theme-octopress version v0.4.5 (commit 5a85834d2d16115928803baad77b12a3f6b490e4)

 1. ./grainw create-post "GORM for SQLaddicts: WHERE Clause"
 2. /grainw

# The error

```bash
$ ./grainw 
16:32:50.349 [main] INFO  c.sysgears.grain.init.ToolsExtractor - Grain version: 0.6.6
16:32:50.352 [main] INFO  c.sysgears.grain.init.ToolsExtractor - Using tools home: /Users/emmanuelrosa/.grain/tools/d9cba5b8bf3d86c6deb58d28073d9fbc
16:32:51.694 [main] INFO  c.s.grain.config.ConfigUpdater - Rereading config /Users/emmanuelrosa/projects/emmanuelrosa.com/SiteConfig.groovy
16:32:53.477 [main] INFO  c.s.grain.config.ConfigUpdater - Development environment is used
16:32:53.521 [main] INFO  c.sysgears.grain.config.ConfigBinder - Switching from com.sysgears.grain.rpc.python.AutoPython to com.sysgears.grain.rpc.python.Jython service for python.interpreter
16:32:53.698 [main] INFO  c.sysgears.grain.config.ConfigBinder - Switching from com.sysgears.grain.rpc.ruby.AutoRuby to com.sysgears.grain.rpc.ruby.JRuby service for ruby.interpreter
16:32:53.827 [Actor Thread 1] INFO  c.s.grain.preview.SitePreviewer - Building resource registry...
16:32:53.828 [Actor Thread 4] INFO  com.sysgears.grain.registry.Registry - Starting resource scan
16:32:54.044 [Actor Thread 2] INFO  c.s.grain.css.compass.RubyCompass - Launching Ruby Compass process...
16:32:54.045 [Actor Thread 5] INFO  com.sysgears.grain.rpc.ruby.JRuby - Launching JRuby process...
16:32:54.119 [Actor Thread 5] INFO  com.sysgears.grain.rpc.ruby.JRuby - /Users/emmanuelrosa/.grain/tools/d9cba5b8bf3d86c6deb58d28073d9fbc/ruby-ipc/ipc.rb 65535
16:32:54.271 [Actor Thread 4] INFO  com.sysgears.grain.registry.Registry - Finished resource scan
16:32:54.279 [Actor Thread 1] INFO  c.s.grain.registry.URLRegistry - Rebuilding url->resource map
java.lang.NullPointerException: Cannot invoke method encodeAsSlug() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:77)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at com.sysgears.octopress.mapping.ResourceMapper.getPostUrl(ResourceMapper.groovy:187)
	at com.sysgears.octopress.mapping.ResourceMapper.this$2$getPostUrl(ResourceMapper.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:361)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
	at com.sysgears.octopress.mapping.ResourceMapper$_closure4.doCall(ResourceMapper.groovy:75)
	at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:959)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.ComposedClosure.call(ComposedClosure.java:103)
	at groovy.lang.Closure.call(Closure.java:439)
	at groovy.lang.Closure.leftShift(Closure.java:683)
	at groovy.lang.Closure$leftShift$1.call(Unknown Source)
	at com.sysgears.octopress.mapping.ResourceMapper$_closure1_closure8.doCall(ResourceMapper.groovy:36)
	at sun.reflect.GeneratedMethodAccessor116.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:2219)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:2189)
	at org.codehaus.groovy.runtime.dgm$61.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.sysgears.octopress.mapping.ResourceMapper$_closure1.doCall(ResourceMapper.groovy:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at com.sysgears.grain.registry.URLRegistry.rebuildUrlResourceMap(URLRegistry.groovy:95)
	at com.sysgears.grain.registry.URLRegistry.this$2$rebuildUrlResourceMap(URLRegistry.groovy)
	at com.sysgears.grain.registry.URLRegistry$this$2$rebuildUrlResourceMap.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
	at com.sysgears.grain.registry.URLRegistry.siteChanged(URLRegistry.groovy:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:901)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:884)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:164)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSafe(ScriptBytecodeAdapter.java:172)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSpreadSafe(ScriptBytecodeAdapter.java:179)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethod0SpreadSafe(ScriptBytecodeAdapter.java:194)
	at com.sysgears.grain.preview.SiteChangeBroadcaster.siteChanged(SiteChangeBroadcaster.groovy:44)
	at com.sysgears.grain.preview.SiteChangeListener$siteChanged.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at com.sysgears.grain.preview.SitePreviewer.start(SitePreviewer.groovy:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at org.codehaus.groovy.reflection.CachedMethod$invoke.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.reflection.CachedMethod$invoke.call(Unknown Source)
	at com.sysgears.grain.service.ServiceManager$ServiceAgent.invokeOriginal(ServiceManager.groovy:226)
	at com.sysgears.grain.service.ServiceManager$ServiceAgent.invokeOriginal(ServiceManager.groovy:224)
	at com.sysgears.grain.service.ServiceManager$ServiceAgent.serviceStart(ServiceManager.groovy:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:361)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:145)
	at com.sysgears.grain.service.ServiceManager$_ServiceAgent_handleMethod_closure4.doCall(ServiceManager.groovy:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:272)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at groovyx.gpars.agent.AgentBase$2.call(AgentBase.java:209)
	at groovyx.gpars.agent.AgentBase.onMessage(AgentBase.java:102)
	at groovyx.gpars.agent.Agent.handleMessage(Agent.java:84)
	at groovyx.gpars.agent.AgentCore$1.handleMessage(AgentCore.java:46)
	at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
16:32:56.353 [Actor Thread 1] INFO  c.s.grain.preview.SitePreviewer - Starting Jetty on http://localhost:4000, press Ctrl+C to stop.
16:32:56.416 [Actor Thread 1] INFO  org.eclipse.jetty.server.Server - jetty-8.1.8.v20121106
16:32:56.463 [Actor Thread 1] INFO  o.e.jetty.server.AbstractConnector - Started SelectChannelConnector@0.0.0.0:4000
16:32:56.464 [main] INFO  com.sysgears.grain.Application - Total time: 5198
16:32:56.465 [main] INFO  com.sysgears.grain.Application - Press CTRL-C or 'q' and ENTER to Stop Grain
16:32:57.196 [Thread-12] INFO  c.s.grain.log.LoggingOutputStream - Starting Ruby IPC on port 65535
16:33:06.103 [RubyThread-26: /Users/emmanuelrosa/.grain/tools/d9cba5b8bf3d86c6deb58d28073d9fbc/compass-bridge/compass_bridge.rb:6] INFO  c.s.grain.log.LoggingOutputStream - >>> Compass is polling for changes. Press Ctrl-C to Stop.
16:33:15.391 [qtp1597598773-81] INFO  / - com.sysgears.grain.preview.GrainServlet-1: GrainServlet initialized```

**Comment by vlasenko** [comment]
Looks like you have some post in your blog that has no title defined. And this results in NPE in ResourceMapper.groovy of Octopress theme at line 187:
 def title = resource.title.encodeAsSlug()

Victor

**Comment by emmanuelrosa** [comment]
Yeah, I had narrowed it down to the same line of code, but I couldn't find anything wrong with my post.

Today I found that the issue is that I use VIM as my text editor and Grain is picking up the the .swp file (ex. *SOMEFILE*.markdown.swp). I guess the .swp extension confuses Grain. Disabling the swap file in VIM with `:set noswapfile` avoids the issue. 

Is there a reason for processing files in *content/blog* with unrecognized file extensions?

**Comment by vlasenko** [comment]
Yes, there is a reason. Pretty much any files with any extension can be processed by Grain. Grain is general purpose static site generator, it is not aware of blogs or other site types, it can be used for any kind of static site. As such it doesn't have the list of "recognized extensions". However you can exclude some files from processing.

Please check section Source Processing Configuration in Grain manual at:
http://sysgears.com/grain/docs/latest/#source-processing-configuration

E.g. you can add
excludes << '.*\.swp$'

**Comment by emmanuelrosa** [comment]
Fantastic. Thank you. I'll go ahead and close this issue.
